### ISSUE TITLE
Import Valuesets from Questionnaire repository

### ISSUE THREAD

**Issue by losolio** [helsenorge/structor#167]
As a form designer I could add and edit Valuesets, so that I could make choice questions. 

- [x] Import Valueset from public available endpoints
- [x] Choose which valusets to include as contained valuesets in questionnaire definition

## About Value Sets:
* [ValueSet](http://hl7.org/fhir/STU3/valueset.html) could be referred to by [Questionnaire.item.options](http://hl7.org/fhir/STU3/questionnaire-definitions.html#Questionnaire.item.options) (choice / open-choice)
* Allowed answers  could be added by [Questionnaire.item.option](http://hl7.org/fhir/STU3/questionnaire-definitions.html#Questionnaire.item.option) (choice / open-choice)
* ValueSet is added in [Questionnaire.contained](http://hl7.org/fhir/STU3/domainresource-definitions.html#DomainResource.contained)

**Comment by GeirLoken** [comment]
[This commit](https://github.com/helsenorge/structor/pull/186/commits/28097373206cf2f91bd094c6381029679a630a16) ensures that valuesets are not shared between questions when importing JSON, as this is currently not supported in the UI. When solving this issue, the commit should be "undone" and shared valueSets should be supported.
