### ISSUE TITLE
Edit linkId for questions/items

### ISSUE THREAD

**Issue by losolio** [helsenorge/structor#213]
> As a form designer I could edit the linkId for each item in the questionnaire so that the linkId has a sepcific value

For postprocessing and enableWhens the logic might be easer to read by developers if the linkId has a good name.

**Comment by jBraekke** [comment]
Is this necessary?

**Comment by losolio** [comment]
Yes, use cases: 

* Making a new version of a questionnaire in structor, and keep the Questionnaire Response as is. 
* Making questionnaires where recipient has business logic depending on linkid in questionnaire response. 
* Hand coding complex and/or nested enableWhens is much easier with human-friendly linkids

**Comment by losolio** [comment]
Solved in #0c13c3893f591736a3f591c5027c5569209207d6
