### ISSUE TITLE
Auto save?

### ISSUE THREAD

**Issue by MariaNHN** [helsenorge/structor#225]
I'm used to auto save from O365, which sometimes makes me forget to click save...and then loose the latest work.

**Comment by GeirLoken** [comment]
First version will use IndexedDB in the browser for storage. 
The entire questionnaire is saved to IndexedDB on every change made in Structor. If accidentally closing the tab/window or navigating away from Structor while editing a questionnaire, the user will be prompted to restore the questionnaire the next time Structor is opened.

Known issues:
- Editing in multiple tabs/windows will most likely cause problems. Changes made in different tabs/windows will overwrite each other and the last changed questionnaire will always be stored in IndexedDB.
- If using the browsers "incognito mode" the IndexedDB is cleared when closing the tab/window and data cannot be restored.

**Comment by losolio** [comment]
Closing as solved!
