### ISSUE TITLE
Form version

### ISSUE THREAD

**Issue by MariaNHN** [helsenorge/structor#229]
How to keep track of the different versions of a form, and go back to an earlier version of the form? Would be great with a version overview that shows earlier versions (with date and who published it), that updates automatically when a new version is published. But for now if that is lots of work, maybe just add a field where version number can be manually updated?

**Comment by GeirLoken** [comment]
Fixed by #278 
https://github.com/helsenorge/structor/pull/278/commits/59eb05be84c7aebf5e384e6774b6964ab7923895
