### ISSUE TITLE
Field for date

### ISSUE THREAD

**Issue by MariaNHN** [helsenorge/structor#231]
The excel way of developing forms, has a field for Date, where the date for last update of the form is written manually. I guess if there was an automatically updated version list (issue 229), we would not need a field for this. But as long as there is no version list for the forms, we could use a normal date field and add it manually.

**Comment by GeirLoken** [comment]
@MariaNHN Another option is to update "lastUpdated" to current date/time when saving. That way we don't need to add a field for "manual entry". What would you prefer?

**Comment by MariaNHN** [comment]
Sounds like a good idea, I don't think the manually field will be actually updated very often... I will double check this with Kim, in case there is some reason why it should not be updated automatically...

**Comment by losolio** [comment]
Epic #171

**Comment by losolio** [comment]
Delivered in #260.
