### ISSUE TITLE
Read only, hidden, Initial and EntryFormat

### ISSUE THREAD

**Issue by MariaNHN** [helsenorge/structor#233]
(Let me know if you want me to split this into 4 issues)

**Read Only** (true/false) - fields that cannot be edited, only viewed (e.g. for calculations)

**Hidden** - fields that are hidden for the user, but e.g. sent to the form receiver or used for calculations. For example, it can be a check for man/woman, or if the form is sent on behalf of (context). 

**Initial** - a field can be prefilled, e.g. a value or a choice from a value set

**EntryFormat** - "shaddowtext" that indicates the expected input . In dropdown lists it can be e.g. "Select"

**Comment by GeirLoken** [comment]
@MariaNHN This is a duplicate. **Read Only** and **Initial** are covered by #172 and **Hidden**/**EntryFormat** are extensions covered by #168
