### ISSUE TITLE
[feat] Change/rearrange/delete options for options questions.

### ISSUE THREAD

**Issue by MariaNHN** [helsenorge/structor#236]
How do I delete one of the first two options, they dont have "x" for delete? See printscreen.

![image](https://user-images.githubusercontent.com/77841246/106735426-8152d300-6614-11eb-8162-58d4a816e037.png)

**Comment by losolio** [comment]
The reason for this is that a choice questions should have at least two options. But I do agree that it may be any two options. Ideally we should validate that the question has at least two options, and allow any option to be deleted.

**Comment by MariaNHN** [comment]
Yes, we need to allow any option to be deleted. Now I had to cut/paste the other options up, but then the enable whens got messed up... It must also be possible to rearrange the options, without having to change the enablewhens... (Move up/down like the items in the overview).
