### ISSUE TITLE
EnableWhen Yes or No

### ISSUE THREAD

**Issue by MariaNHN** [helsenorge/structor#237]
I created a Yes/No question, and then wanted a new question to only display if Yes was selected. Maybe I did something wrong, but could not find Yes and No as options in the EnableWhen. See printscreens in attachment. 
[EnableWhenYesOrNo.docx](https://github.com/helsenorge/structor/files/5931728/EnableWhenYesOrNo.docx)

**Comment by mgunnerud** [comment]
This is a bug in the JSON generated; according to the FHIR specifications, an item cannot have both "answerValueSet" and "answerOption". 

- If "prefedinerte alternativer..." is chosen, the item must have the "answerValueSet" property and NOT the "answerOption" property.
- If "Flere alternativer..." is chosen, the item must have the "answerOption" property  and NOT the "answerValueSet" property.

**Comment by losolio** [comment]
Closing this in favor of #220.
