### ISSUE TITLE
Questions - text format

### ISSUE THREAD

**Issue by MariaNHN** [helsenorge/structor#239]
All the different fields should have the same text format on the question, see printscreen:

![image](https://user-images.githubusercontent.com/77841246/107232716-04fc2d80-6a22-11eb-9892-62cffebf7b3b.png)

**Comment by losolio** [comment]
@MariaNHN Not sure here if I did understand what you ment was wrong?

**Comment by MariaNHN** [comment]
The second question seems to be bold, the first one not. Should be the same default format on all questions.

**Comment by losolio** [comment]
@MariaNHN Could you post the form definition generated by structor? Either here or at Slack?

**Comment by mgunnerud** [comment]
This is the default label styling of radio-group and checkbox-group from @helsenorge/toolkit. All other field types have bold label. Must be changed in @helsenorge/toolkit, or an exception from this design can be made in @helsenorge/skjemautfyller.

**Comment by losolio** [comment]
Closing this, as it is related to the form filler, and not to the form designer. @MariaNHN - the solution would be to mark the first question as bold in the markdown editor to achieve consistent look in Helsenorge Form Filler.
