### ISSUE TITLE
Error msg. when uploading to test (int)

### ISSUE THREAD

**Issue by MariaNHN** [helsenorge/structor#241]
I created a form in Skjemabyggeren, and it looks fine in the preview. But when uploading it to int/mas02 in cmd, I get this error msg.:

fail: FhirTool.Program[0]
      Parser: The property 'answerValueSet' has an empty string value, which is not allowed. (at line 1, 1671)

Have you been able to upload forms to int/mas02 without getting this error, or is it just me? It happened last time I tried to upload to also, on another form. It should not be necessary to manually remove all the "answerValueSet" from the json.

Printscreens:
![image](https://user-images.githubusercontent.com/77841246/107354899-0a638180-6acf-11eb-96a3-798c95c00b34.png)

![image](https://user-images.githubusercontent.com/77841246/107354936-151e1680-6acf-11eb-96ab-625e48a5ee92.png)
[](url)

**Comment by losolio** [comment]
Not sure when this `answerValueSet` is added. Maybe we could just remove it if is empty?

See also #237.

**Comment by losolio** [comment]
We do hope that #2220 solves this, if not please reopen.
