### ISSUE TITLE
GUI improvements 

### ISSUE THREAD

**Issue by MariaNHN** [helsenorge/structor#245]
I have collected some input in the attachment, on how to maybe make it even more user friendly.
[Forslag brukervennlighet.docx](https://github.com/helsenorge/structor/files/5980660/Forslag.brukervennlighet.docx)

- [x] Ha label på skjematittel
- [x] Flytt "Beskrivelse av skjema" til skjemadetaljer, og kall feltet beskrivelse
- [x] I skjemadetaljer: Navn => Teknisk navn. Vurder supplerende info/validering om ikke mellomrom eller spesialtegn
- [x] Legg til betinget visning => Betinget visning. Forklaring Sett betingelser for visning av spørsmålet 
- [x] Bytte fra ordet spørsmål til element der det passer bedre
- [x] Vis spørsmålsnummer sammen med spørsmålstekst i dropdown for å velge tidligere spørsmål i betinget visning

Vurder å ha skjemadetaljer som meny.

**Comment by losolio** [comment]
All in!
