### ISSUE TITLE
Oppfølgningsspørsmål av typen alternativer>checkbox forsvinner 

### ISSUE THREAD

**Issue by losolio** [helsenorge/structor#251]
**Describe the bug**
Når man legger til et oppfølgningsspørsmål med checkbox til en gruppe, så forsvinner spørsmålet

**To Reproduce**
1. Lage et nytt skjema
2. Lag en gruppe
2. Lag et oppfølgningsspørsmål
3. Velg Flere alternativer 
4. Merk at det skal være Checkbox
5. Spørsmålet forsvinner

**Expected behavior**
Spørsmålet er fortsatt i skjemaet

**Comment by MariaNHN** [comment]
I mitt skjema har et checkbox-element forsvunnet, uten at det var i noen gruppe. Usikker på om det var oppfølgingsspørsmål eller ikke, tror kanskje ikke det. Element 3 vises i skjemaoversikten og forhåndsvisningen, men ikke i selve hovedfeltet i skjemabyggeren. Har sendt json til Ole, fikk ikke legge det som vedlegg her.
