### ISSUE TITLE
Select type of buttons

### ISSUE THREAD

**Issue by MariaNHN** [helsenorge/structor#256]
In "Skjemadetaljer" I would like to choose if the buttons should be static (fast), sticky (flytende) or none (ingen knapper). Currently (in excel) the column "PresentationButtons" is used for this.

**Comment by losolio** [comment]
@MariaNHN Could you provide an example on how the json looks when setting this in excel?

**Comment by MariaNHN** [comment]
In excel:
![image](https://user-images.githubusercontent.com/77841246/109148233-43a21f80-7766-11eb-8c42-b30a4360355d.png)
On the form:
![image](https://user-images.githubusercontent.com/77841246/109148270-561c5900-7766-11eb-9c27-93e4e7d6a71a.png)

**Comment by losolio** [comment]
@MariaNHN i prod nå 🥳
