### ISSUE TITLE
Set value for the CanBePerformedBy extension

### ISSUE THREAD

**Issue by MariaNHN** [helsenorge/structor#257]
Some forms allow for others to send in on behalf of others, some not. 

Seems like the default is to allow for this, and then this text is displayed on the form: "Velg Om skjema hvis du har spørsmål eller ønsker å fylle ut på vegne av andre enn deg selv. Her finner du informasjon om hvor du kan henvende deg og hvordan opplysningene du oppgir vil bli behandlet."

Some forms (like helsetrygdkort) does not allow for this (in the first version), so we need to turn it off. 

Currently (in excel) I think the column CanBePerformedBy is used for this.

**Comment by losolio** [comment]
Part of this epic #171. Should be a setting in "Skjemadetaljer".

**Comment by MariaNHN** [comment]
Can you confirm that when CanBePerformedBy is off (cannot send on behalf of), then these two wil automatically not be displayed?

![image](https://user-images.githubusercontent.com/77841246/108981866-75938300-768d-11eb-9351-7b5ca1b0ea43.png)

**Comment by MariaNHN** [comment]
Update: The green information box is still there when on-behalf-of, but it displays a different text. Here you see a form that cannot be sent in on behalf of others: https://tjenester-hn-mas-02.int-hn.nhn.no/skjemautfyller/?Query=Questionnaire%2f500

**Comment by losolio** [comment]
Ute nå, @MariaNHN 🤩
