### ISSUE TITLE
Left margin and frame missing

### ISSUE THREAD

**Issue by MariaNHN** [helsenorge/structor#258]
When adding Fødselsnummer in json-code, this is displayed without the frame and therefore is not left aligned like the other elements. Used in Helsetrygdkort, so it is a little urgent to fix.

![image](https://user-images.githubusercontent.com/77841246/108680700-793cd380-74ee-11eb-96db-e0cddb210560.png)

**Comment by losolio** [comment]
@MariaNHN  It is a bit little info on this, feel free to send json on slack.. Perhaps put the social security number inside a group?

**Comment by losolio** [comment]
Closing this, as does seem to be an related to the form filler.
