### ISSUE TITLE
Placing of the help icon

### ISSUE THREAD

**Issue by MariaNHN** [helsenorge/structor#259]
The help icon is currently displayed under the question, instead of to the right:
![image](https://user-images.githubusercontent.com/77841246/108681712-c2415780-74ef-11eb-8865-0d64f966cd40.png)

**Comment by mgunnerud** [comment]
When using markdown for label text, this can happen. It must be fixed in the form filler code.

**Comment by losolio** [comment]
Closing this, as not related to form builder.
