### ISSUE TITLE
Markdown on help text

### ISSUE THREAD

**Issue by MariaNHN** [helsenorge/structor#263]
With excel it is possible to format the text in the help box (see printscreen), we will therefore also need this functionality in Skjemabyggeren.
 
![image](https://user-images.githubusercontent.com/77841246/108720732-7b6c5580-7521-11eb-9655-78042e391329.png)

**Comment by MariaNHN** [comment]
In json it looks like this. Let me know if you need the entire json file and I can send it in an email. Not possible to add json here...
![image](https://user-images.githubusercontent.com/77841246/108826077-2d5c5e00-75c4-11eb-8f6c-ec7a3491fea9.png)

**Comment by losolio** [comment]
@jBraekke til info :)

**Comment by jBraekke** [comment]
Done

**Comment by losolio** [comment]
Da er denne levert, @MariaNHN 🥳
