### ISSUE TITLE
Change date field

### ISSUE THREAD

**Issue by MariaNHN** [helsenorge/structor#271]
The date field in Skjemadetaljer is currently set to todays date, we need to change this to be a manual date field. 

It will be used to put in date for when the form was last put in production. The text over can be "Dato for sist produksjonssetting" or something like that?

Sorry for not updating this before!

**Comment by losolio** [comment]
@MariaNHN Could you provide the steps to reproduce this issue?

**Comment by losolio** [comment]
Closing as solved as clarified on Slack.
