### ISSUE TITLE
No-Break Space gives error when submitting form

### ISSUE THREAD

**Issue by MariaNHN** [helsenorge/structor#280]
When pasting in text (e.g. from Word), and the text contains this invisible character (see printscreen), I get error message when sending in the form with endpoint/40. Kenneth think that it is the validation of the xml that does not like the Non-Break Space.

1. Copy some text from Word that contains Non-Break Space
2. Paste the text in an element (e.g. Beskjed) 
3. Add endpoint/40 as endpoint to the form
4. Save the form and upload to e.g. mas02
5. Try to submit the form

![image](https://user-images.githubusercontent.com/77841246/110464047-f19cba80-80d2-11eb-8d4f-ca5d149aa672.png)

Får dere opp json her? 
https://gist.github.com/MariaNHN/5bab9a2fbe2edf9eb289451302acef52

I think you need to use Linux to see the invisible character, Windows hides it...

**Comment by losolio** [comment]
@kennethmyhra Could you take a look into this: is this structor behaving badly, or should this be solved another place?

**Comment by kennethmyhra** [comment]
@losolio the theory is that the Markdown editor you are using is doing this

**Comment by kennethmyhra** [comment]
I am closing this for now, we will try to fix this by changing `fhir-single.xsd` as conferenced on FHIR Chat

For reference:
* https://chat.fhir.org/#narrow/stream/179166-implementers/topic/markdown-primitive.20regex
* https://dev.azure.com/nhnfelles/Helsenorge/_workitems/edit/250960
