### ISSUE TITLE
Bug in the "Flytt til element" drop down when using two screens

### ISSUE THREAD

**Issue by MariaNHN** [helsenorge/structor#292]
To reproduce the error:
1. Use two screens
2. Open a form with some elements in the Skjemabygger on one of the screens
3. On one of the elements, open "Avanserte innstillinger" and then open the drop down menu for "Flytt til element"
4. The content in the drop-down will then be displayed over both screens

Printscreen: 
![image](https://user-images.githubusercontent.com/77841246/111640621-a4b89280-87fc-11eb-998a-9c81fdb47906.png)

**Comment by losolio** [comment]
Seems to be related to browser, and not structor? Closing this for now.
