### ISSUE TITLE
Translate choices/options

### ISSUE THREAD

**Issue by MariaNHN** [helsenorge/structor#293]
How do I translate the options to other languages?

1. Create a new form
2. Add an element "Alternativer
3. Put in the question text, and some options that the user can choose between
4. Add a language to the form, e.g. English
5. Translate the content of the form. There is nowhere to translate the options you added in step 3
6. Preview the form, and compare the two languages. The options are missing in English

![image](https://user-images.githubusercontent.com/77841246/111971763-f9118a00-8afc-11eb-910b-bb83521ba14a.png)

**Comment by GeirLoken** [comment]
@MariaNHN Is this still an issue? Seems to be fixed:
![image](https://user-images.githubusercontent.com/43747501/113702358-b0032d80-96d9-11eb-83e8-33224062641f.png)

**Comment by MariaNHN** [comment]
Yes, it works now :)
