### ISSUE TITLE
Check if user is on-behalf-of or not

### ISSUE THREAD

**Issue by MariaNHN** [helsenorge/structor#305]
Some forms contain a check on whether the user is filling in the form on behalf of someone else or not. 

In Excel this is done by a hidden boolean with this code:
![image](https://user-images.githubusercontent.com/77841246/112283938-f5ab0980-8c88-11eb-88b8-058cdb9cc238.png)

This check is used e.g. like this:
**If** I am filling in the form on behalf of my child (boolean=true), **then**  information about my child is displayed in the form.

In Excel - we need to put this row inside a group. Not sure if this is a problem for Skjemabyggeren or not. But if we place this check in the top of the form (not in a group), information about the child will not be displayed on the PDF.

**Comment by losolio** [comment]
Seems to be solved! Please reopen if not! :)
