### ISSUE TITLE
Bug when using none buttons

### ISSUE THREAD

**Issue by MariaNHN** [helsenorge/structor#309]
In Skjemadetaljer I can choose that the form should have no buttons. But forms with this option only display the header and  no content in the form. 

To reproduce:
1. Create a new form in Skjemabyggeren
2. In Skjemadetaljer, select "Ingen" in "Visning av knapperad"
3. Add some elements, e.g. a Beskjed
4. Upload to test environment and open it in your brower
5. Only the title of the form is displayed

**Comment by mgunnerud** [comment]
Bug in Helsenorge skjemautfyller
