### ISSUE TITLE
Too small text field in preview

### ISSUE THREAD

**Issue by MariaNHN** [helsenorge/structor#319]
When using "Langsvar", the text box in preview is too small. 

1. Create a form with a Langsvar element
2. Add a lot of text in the text box
3. The text box is too small and the text is displayed outside it

![image](https://user-images.githubusercontent.com/77841246/112983271-c94a2e00-915d-11eb-99cf-e415ad09af10.png)

**Comment by mgunnerud** [comment]
Fixed by PR #321
