### ISSUE TITLE
Change of the element "Alternativer med åpent svar"

### ISSUE THREAD

**Issue by MariaNHN** [helsenorge/structor#322]
When usint "Alternativer med åpent svar", an additional checkbox/optionbutton with the text "annet" is added. When selecting this, a textbox is displayed, with a header that is a copy of the question text in the element. 

Instead, we want: 
1. "Annet" is displayed with a capital "A" instead of "a"
2. The question text over the "Annet" textbox should be possible to edit for the user

![image](https://user-images.githubusercontent.com/77841246/113689800-fd2bd300-96ca-11eb-86f7-c65160b71e76.png)

**Comment by mgunnerud** [comment]
@MariaNHN These labels are hardcoded in skjemautfyller. Can you create a bug or change request for this in NHN Azure Devops?

**Comment by mgunnerud** [comment]
Fixed by #325
