### ISSUE TITLE
System must be a uri

### ISSUE THREAD

**Issue by mgunnerud** [helsenorge/structor#326]
According to the FHIR documentation, Coding.system should be a uri: http://hl7.org/fhir/datatypes.html#Coding

Auto-generated system should then look something like: **urn:uuid:53fefa32-fcbb-4ff8-8a92-55ee120877b7** instead of the system we generate today: 53fefa32-fcbb-4ff8-8a92-55ee120877b7-system

Also consider validating that the system is a uri when it is changed by the user in the UI.

**Comment by losolio** [comment]
Closing as solved!
