### ISSUE TITLE
Custom validation text is not displayed

### ISSUE THREAD

**Issue by MariaNHN** [helsenorge/structor#339]
When adding a custom validation text, it is still the default one that is displayed

To reproduce:
1. Create new form
2. Add an element with validation, eg. Kortsvar
3. Add validation, eg. max 5 characters
4. Add a custom validation text
5. Go to preview and try to type in more than max allowed characters
The error text displayed is the default one, not the custom one

![image](https://user-images.githubusercontent.com/77841246/115218200-94028180-a106-11eb-930b-2fda126f3980.png)

**Comment by mgunnerud** [comment]
Looks like the text-field component in toolkit does not support this. Validation error message for max-length is always the hardcoded string. This should be handled as a change request for skjemautfyller in Azure Devops.

**Comment by mgunnerud** [comment]
@MariaNHN ref my comment above, this is not a bug in strutor; but rather in the Helsenorge implementation. Closing.
