### ISSUE TITLE
AuthenticationRequirement

### ISSUE THREAD

**Issue by MariaNHN** [helsenorge/structor#347]
A property that decides whether the form can be sent in without logging in or not. Should be placed in Skjemadetaljer.

Three possible choices:

1 = Anonymous 
2 = Optional
3 = Required

**Comment by losolio** [comment]
Example on extension definiton on questionnaire level: 

```json
    {
      "url": "http://ehelse.no/fhir/StructureDefinition/sdf-authenticationrequirement",
      "valueCoding": {
        "system": "http://ehelse.no/fhir/ValueSet/AuthenticationRequirement",
        "code": "3"
      }
    }
```
