### ISSUE TITLE
Dropdown list element

### ISSUE THREAD

**Issue by MariaNHN** [helsenorge/structor#348]
It should be possible to create a dropdown list. I think we had this element available earlier, but I might be wrong...

**Comment by losolio** [comment]
@mgunnerud legger du til et eksempel på item-control dropdown json?

**Comment by MariaNHN** [comment]
@mgunnerud  @losolio  Eksempel: https://gist.github.com/MariaNHN/9c0f7bcfe54521721e2784945cb35967 (søk drop-down)

**Comment by mgunnerud** [comment]
Extension for drop-down (brukes på type === choice og type === open-choice). Disse støtter også questionnaire-item-control radio og checkbox:

```

   "extension":[
      {
         "url":"http://hl7.org/fhir/StructureDefinition/questionnaire-itemControl",
         "valueCodeableConcept":{
            "coding":[
               {
                  "system":"http://hl7.org/fhir/ValueSet/questionnaire-item-control",
                  "code":"drop-down"
               }
            ]
         }
      }
   ]

```

**Comment by MariaNHN** [comment]
Ganske sikker på at vi hadde elementet "Nedtrekksmeny" tidligere, kan det ha forsvunnet når mottakerlisten kom inn? Mulig jeg husker heelt feil, men i tilfelle det allerede er laget noe på dette som kan "plukkes opp" igjen... :)
