### ISSUE TITLE
BMI calculation not working

### ISSUE THREAD

**Issue by MariaNHN** [helsenorge/structor#361]
When using the BMI calculation, the calculated BMI should be displayed. Instead we get "Ikke besvart". 
https://gist.github.com/MariaNHN/5ad0165b615c634539a3a89613651911 
https://minhelse.hn2.test.nhn.no/skjemautfyller?pnr=01126222358&Query=Questionnaire%2F400

![image](https://user-images.githubusercontent.com/77841246/117626116-0f3fdc00-b177-11eb-908e-aafb93f3f26f.png)

It works in the old form: 
https://minhelse.hn2.test.nhn.no/skjemautfyller?pnr=01126222358&Query=Questionnaire%2F400

![image](https://user-images.githubusercontent.com/77841246/117627453-790cb580-b178-11eb-9d29-29e315400da0.png)

This might be the reason why we get error msg. when trying to send in this form in MAS02

**Comment by mgunnerud** [comment]
Bug fixed in Helsenorge form filler.
