### ISSUE TITLE
Sublabels

### ISSUE THREAD

**Issue by MariaNHN** [helsenorge/structor#366]
Possibility to add a sublabel (between label and input field), by using Skjemabyggeren: 

Details: https://dev.azure.com/nhnfelles/Helsenorge/_workitems/edit/250824/

The new property can be called "Instruks".

**Register time for this task on 10000012 -  melde.no - pasienter og pårørende**

**Comment by kennethmyhra** [comment]
Commit for sublabel extension: https://github.com/helsenorge/fhir-sdf/commit/6a19e49807f4538fad56774a173fda9074376044. Ny npm-pakke på vei ut
