### ISSUE TITLE
Support for uploading valuesets as json

### ISSUE THREAD

**Issue by vadi2** [helsenorge/structor#398]
It would be great if I could upload valuesets as json files - as far as I see I have to pass a URL to a hosted one right now. 

In a similar vein, it would be great if I could upload jsons for both questionnaires and valuesets in one go - that way I can select everything I need from a prepared folder (say, SUSHI output) and load it up.

**Comment by mgunnerud** [comment]
Hi, thank you for the issue report! This is a feature we have already discussed, and it is on our todo-list. I will try to implement it next week.
