### ISSUE TITLE
Support multi-lingual questionnaire definitions

### ISSUE THREAD

**Issue by litlfred** [helsenorge/structor#412]
Are there any plans to support multi-lingual questionnaire editing in the roadmap?   I didn't see anything in the demo.   

SDC has guidance on extensions for translations here:
   http://hl7.org/fhir/uv/sdc/2019May/sdc-questionnaire.html#language-and-translations

Thanks in advance for any information you can provide.

**Comment by kennethmyhra** [comment]
Hey, we support translations.

You can open up the translation part from (i) icon on the left side

![image](https://user-images.githubusercontent.com/248795/154687977-60676132-ec3e-4890-86ad-c2c0a5d9dc39.png)

![image](https://user-images.githubusercontent.com/248795/154688065-e271d5e2-d522-4316-9d04-5c5385033b72.png)

**Comment by litlfred** [comment]
OK.  Wonderful!  Sorry that I missed that.

**Comment by litlfred** [comment]
@kennethmyhra  thanks again for responding on this message.   we (WHO) have been exploring the use of structor in a few projects as part of our SMART Guidlelines work:

**Comment by kennethmyhra** [comment]
@litlfred Of course. You can start by contacting me at kenneth.myhra at nhn.no
