### ISSUE TITLE
Rich Text Editor (RTE) License compatibility

### ISSUE THREAD

**Issue by imanesaurus** [helsenorge/structor#483]
**Is your feature request related to a problem? Please describe.**
Hi, I would like to bring to your attention a matter related to the license used by the Rich Text Editor (RTE) in Structor. I have noticed that the current RTE implementation utilizes CKEditor, which is licensed under the GNU General Public License (GPL). On the other hand, Structor itself is licensed under the permissive MIT License.

**Describe the solution you'd like**
The use of CKEditor's GPL license in conjunction with Structor's MIT License may raise certain concerns related to compliance and potential licensing issues. To address this, I would like to propose an alternative solution. It would be beneficial to consider adopting a more widely-used RTE like Draft.js, which is hosted at https://github.com/facebookarchive/draft-js and also carries the MIT License.

By transitioning to a non-GPL licensed RTE, we can align with Structor's permissive MIT License and potentially avoid any licensing complexities. Draft.js presents itself as a popular and well-supported option that is in line with our licensing requirements.

In support of this proposition, I am more than willing to contribute to the implementation and create a Pull Request (PR) to facilitate the necessary changes.

**Additional context**
I kindly request your consideration of this proposal and would be pleased to discuss further details or provide any additional context if needed.

**Comment by AG-83** [comment]
Hi @imanesaurus 
We are looking at the issue.

**Comment by kennethmyhra** [comment]
We are allowed to use GPL licensed components, libraries, etc even though we ourselves license Structor under MIT as long as we make the code available, like we have done by open sourcing Structor's code.

>If you distribute YOUR APPLICATION, and you used something GPL as part of your application (even if only linking at run-time to a library) - and even if you do not charge money - and even if you do not change that GPL s/w in any way - then you MUST make the source of YOUR APPLICATION available.
